/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    id("maven-publish")
    signing
    id("org.cyclonedx.bom") version "3.1.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin Test integration.
    testImplementation(kotlin("test"))

    // Use the JUnit 5 integration.
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.10.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }

    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11

    withJavadocJar()
    withSourcesJar()
}

// Apply a specific Kotlin toolchain to ease working on different environments.

kotlin {
    jvmToolchain(21)
    explicitApi()
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11)

        freeCompilerArgs.addAll("-Xjsr305=strict")
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])

            groupId = "phd.pranam"
            artifactId = "digipin"
            version = project.version.toString()

            pom {
                name.set("digipin")
                description.set("Kotlin library for encoding and decoding DIGIPIN (Digital Postal Index Number)")
                url.set("https://github.com/pranamphd/digipin-kotlin")

                licenses {
                    license {
                        name.set("Apache License, Version 2.0")
                        url.set("http://www.apache.org/licenses/LICENSE-2.0")
                    }
                }

                developers {
                    developer {
                        id.set("pranamphd")
                        name.set("Pranam")
                        email.set("pranam@pranam.phd")

                        organization.set("Pranam")
                        organizationUrl.set("https://orcid.org/0009-0007-9316-3616")
                    }
                }



                scm {
                    url.set("https://github.com/pranamphd/digipin-kotlin")
                    connection.set("scm:git:https://github.com/pranamphd/digipin-kotlin.git")
                    developerConnection.set("scm:git:ssh://git@github.com:pranamphd/digipin-kotlin.git")
                }
            }
        }
    }

    repositories {
        maven {
            name = "Central"
            url = uri("https://central.sonatype.com/api/v1/publisher")

            credentials {
                username = System.getenv("CENTRAL_USERNAME")
                password = System.getenv("CENTRAL_PASSWORD")
            }
        }
    }
}

val signingRequired = providers.environmentVariable("GPG_PRIVATE_KEY")
    .zip(providers.environmentVariable("GPG_PRIVATE_KEY_PASSWORD")) { _, _ -> true }.orElse(false)

signing {
    isRequired = signingRequired.get()

    if (isRequired) {
        useInMemoryPgpKeys(
            providers.environmentVariable("GPG_PRIVATE_KEY").get(),
            providers.environmentVariable("GPG_PRIVATE_KEY_PASSWORD").get()
        )
    }

//    useGpgCmd()
    sign(publishing.publications)
}

tasks.withType<Jar> {
    isPreserveFileTimestamps = true
    isReproducibleFileOrder = true
}
